### ISSUE TITLE
The requested accessory 'TuyaSmartDevice' was not registered by any plugin.

### ISSUE THREAD

**Issue by tman15bp** [SLaweck/homebridge-tuya-smartlamp#12]
~ % homebridge
[1/3/2020, 15:33:07] Loaded config.json with 1 accessories and 0 platforms.
[1/3/2020, 15:33:08] ---
[1/3/2020, 15:33:10] No plugins found. See the README for information on installing plugins.
[1/3/2020, 15:33:10] Loading 1 accessories...
[1/3/2020, 15:33:10] Error: The requested accessory 'TuyaSmartDevice' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
[1/3/2020, 15:33:10] Got SIGTERM, shutting down Homebridge...
![Screenshot 2020-01-03 at 15 32 37](https://user-images.githubusercontent.com/59480151/71732075-480ec900-2e3e-11ea-9c71-020a87f9591b.png)

**Comment by smtony** [comment]
install with sudo and -g, worked for me.
