### ISSUE TITLE
Bulbs are seen but uncontrollable.

### ISSUE THREAD

**Issue by zang74** [SLaweck/homebridge-tuya-smartlamp#7]
I've 8 new Gosund brand Tuya bulbs. They all have MCU/WiFi versions of 3.3.8 and one with 3.3.3. Homebridge sees all 8 of them, but none are controllable. I'm getting errors. I'm just using one bulb as example here; the errors are the same across all of them.

```[9/22/2019, 12:21:19 PM] [Corner Light] Error: getSchema timeout - no answer from device within 5000 ms [TLB]
[9/22/2019, 12:21:19 PM] [Corner Light] Connection problem - force device disconnect [TLB]
[9/22/2019, 12:21:19 PM] [Corner Light] Error: getting on/off status error timeout error [TLB]
[9/22/2019, 12:21:19 PM] [Corner Light] Error: getting brightness error timeout error [TLB]
[9/22/2019, 12:21:19 PM] [Corner Light] Error: getting on/off status error timeout error [TLB]
[9/22/2019, 12:21:19 PM] [Corner Light] Error: getting color error timeout error [TLB]
[9/22/2019, 12:21:19 PM] [Corner Light] Error: getting color error timeout error [TLB]
[9/22/2019, 12:21:19 PM] [Corner Light] Error: getting color error timeout error [TLB]
[9/22/2019, 12:21:22 PM] [Corner Light] IP address resolved 192.168.0.150 [TLB]
[9/22/2019, 12:21:22 PM] [Corner Light] IP address resolved 192.168.0.150 [TLB]
[9/22/2019, 12:21:22 PM] [Corner Light] IP address resolved 192.168.0.150 [TLB]
[9/22/2019, 12:21:22 PM] [Corner Light] IP address resolved 192.168.0.150 [TLB]
[9/22/2019, 12:21:22 PM] [Corner Light] IP address resolved 192.168.0.150 [TLB]
[9/22/2019, 12:21:27 PM] [Corner Light] Error: Device connect error: Error: connection timed out
    at Socket.client.setTimeout (/usr/local/lib/node_modules/homebridge-tuya-smartlamp/node_modules/tuyapi/index.js:292:18)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) [TLB]
[9/22/2019, 12:21:27 PM] [Corner Light] Error: Device connect error: Error: connection timed out
    at Socket.client.setTimeout (/usr/local/lib/node_modules/homebridge-tuya-smartlamp/node_modules/tuyapi/index.js:292:18)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) [TLB]
[9/22/2019, 12:21:27 PM] [Corner Light] Error: setting color [ 1, 100, 75 ] error device connect error: Error: connection timed out [TLB]
[9/22/2019, 12:21:27 PM] [Corner Light] Error: Device connect error: Error: connection timed out
    at Socket.client.setTimeout (/usr/local/lib/node_modules/homebridge-tuya-smartlamp/node_modules/tuyapi/index.js:292:18)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) [TLB]
[9/22/2019, 12:21:27 PM] [Corner Light] Error: turning off error device connect error: Error: connection timed out [TLB]
```
Is there something I'm missing here?

**Comment by SLaweck** [comment]
Hi
Maybe these bulbs require protocol version 3.3, if yes you should add "version": "3.3" to your config.
